import fs from 'node:fs/promises';
import path from 'node:path';
import { ensureDir, fetchBytes, mimeFromUrl, sleep, safe } from './util.js';
const base='https://generativelanguage.googleapis.com/v1beta';
const key=()=>{if(!process.env.GEMINI_API_KEY)throw new Error('GEMINI_API_KEY missing');return process.env.GEMINI_API_KEY};
async function gj(url,opts={}){ const r=await fetch(url,{...opts,headers:{'x-goog-api-key':key(),'content-type':'application/json',...(opts.headers||{})}}); const text=await r.text(); let j={}; try{j=text?JSON.parse(text):{}}catch{j={raw:text}} if(!r.ok)throw new Error(`Gemini ${r.status}: ${JSON.stringify(j).slice(0,2500)}`); return j; }
export async function generateImage({model,prompt,sources=[],aspectRatio='9:16',imageSize='1K',outFile}){ const parts=[{text:prompt}]; for(const u of sources.slice(0,8)){ const b=await fetchBytes(u); parts.push({inlineData:{mimeType:mimeFromUrl(u),data:b.toString('base64')}}); }
 const body={contents:[{parts}],generationConfig:{responseModalities:['IMAGE'],responseFormat:{image:{aspectRatio,imageSize}}}}; let j; try{j=await gj(`${base}/models/${model}:generateContent`,{method:'POST',body:JSON.stringify(body)});}catch(e){ const fallback={contents:[{parts}],generationConfig:{responseModalities:['IMAGE'],imageConfig:{aspectRatio,imageSize}}}; j=await gj(`${base}/models/${model}:generateContent`,{method:'POST',body:JSON.stringify(fallback)}); }
 const ps=j.candidates?.[0]?.content?.parts||[]; const img=ps.find(p=>p.inlineData?.data); if(!img)throw new Error(`No image returned: ${JSON.stringify(j).slice(0,1000)}`); await ensureDir(path.dirname(outFile)); await fs.writeFile(outFile,Buffer.from(img.inlineData.data,'base64')); return {mime:img.inlineData.mimeType||'image/png'}; }
function inlineImage(buf,mime='image/png'){return {inlineData:{mimeType:mime,data:buf.toString('base64')}}}
export async function generateVideo({model,prompt,mode='T2V',firstImage,lastImage,references=[],extendVideo,aspectRatio='9:16',resolution='720p',duration=4}){ const instance={prompt}; if(firstImage)instance.image=inlineImage(firstImage.buffer,firstImage.mime); if(lastImage)instance.lastFrame=inlineImage(lastImage.buffer,lastImage.mime); if(references.length)instance.referenceImages=references.slice(0,3).map(x=>({image:inlineImage(x.buffer,x.mime),referenceType:'asset'})); if(extendVideo)instance.video={inlineData:{mimeType:'video/mp4',data:extendVideo.toString('base64')}};
 const personGeneration=(mode==='T2V'||mode==='EXTEND')?'allow_all':'allow_adult'; const parameters={aspectRatio,resolution,durationSeconds:String(duration),personGeneration,numberOfVideos:1}; if(mode==='EXTEND'){parameters.resolution='720p';parameters.durationSeconds='8';}
 const start=await gj(`${base}/models/${model}:predictLongRunning`,{method:'POST',body:JSON.stringify({instances:[instance],parameters})}); if(!start.name)throw new Error(`Veo operation missing name: ${JSON.stringify(start)}`); let op=start; while(!op.done){ await sleep(10000); op=await gj(`${base}/${start.name}`); }
 if(op.error)throw new Error(`Veo failed: ${JSON.stringify(op.error)}`); const sample=op.response?.generateVideoResponse?.generatedSamples?.[0] || op.response?.generatedVideos?.[0]; const uri=sample?.video?.uri || sample?.video?.videoUri || sample?.uri; if(!uri)throw new Error(`Veo output URI missing: ${JSON.stringify(op).slice(0,3000)}`); const r=await fetch(uri,{headers:{'x-goog-api-key':key()},redirect:'follow'}); if(!r.ok)throw new Error(`Veo download ${r.status}`); return {operation:start.name,providerUri:uri,bytes:Buffer.from(await r.arrayBuffer())}; }
export async function uploadGeminiFile(filePath,mime='video/mp4'){ const st=await fs.stat(filePath); const start=await fetch(`${base.replace('/v1beta','')}/upload/v1beta/files?key=${encodeURIComponent(key())}`,{method:'POST',headers:{'X-Goog-Upload-Protocol':'resumable','X-Goog-Upload-Command':'start','X-Goog-Upload-Header-Content-Length':String(st.size),'X-Goog-Upload-Header-Content-Type':mime,'Content-Type':'application/json'},body:JSON.stringify({file:{display_name:safe(path.basename(filePath))}})}); if(!start.ok)throw new Error(`Gemini file start ${start.status}: ${await start.text()}`); const uploadUrl=start.headers.get('x-goog-upload-url'); if(!uploadUrl)throw new Error('Gemini upload URL missing'); const data=await fs.readFile(filePath); const up=await fetch(uploadUrl,{method:'POST',headers:{'Content-Length':String(data.length),'X-Goog-Upload-Offset':'0','X-Goog-Upload-Command':'upload, finalize'},body:data}); let j=await up.json(); if(!up.ok)throw new Error(`Gemini upload ${up.status}: ${JSON.stringify(j)}`); let f=j.file; while(f?.state==='PROCESSING'){await sleep(3000); f=await gj(`${base}/${f.name}`);} if(f?.state==='FAILED')throw new Error(`Gemini file processing failed: ${JSON.stringify(f)}`); return f; }
export async function analyzeVideo({filePath,model,prompt}){ const f=await uploadGeminiFile(filePath); const body={contents:[{parts:[{fileData:{mimeType:f.mimeType||'video/mp4',fileUri:f.uri}},{text:prompt}]}],generationConfig:{responseMimeType:'application/json'}}; const j=await gj(`${base}/models/${model}:generateContent`,{method:'POST',body:JSON.stringify(body)}); const text=(j.candidates?.[0]?.content?.parts||[]).map(p=>p.text||'').join('').trim(); const clean=text.replace(/^```json\s*/i,'').replace(/```$/,'').trim(); try{return JSON.parse(clean)}catch{return {score:0,pass:false,notes:`Invalid QC JSON: ${clean.slice(0,800)}`}}; }
