import crypto from 'node:crypto';
import { headerMap, objFromRow, rowFromObj } from './util.js';
let cached={token:null,exp:0};
const b64u=x=>Buffer.from(x).toString('base64url');
function serviceAccount(){ const raw=process.env.GOOGLE_SERVICE_ACCOUNT_JSON; if(!raw)return null; try{return JSON.parse(raw)}catch{} try{return JSON.parse(Buffer.from(raw,'base64').toString('utf8'))}catch{throw new Error('GOOGLE_SERVICE_ACCOUNT_JSON is not valid JSON/base64 JSON');} }
async function token(){ if(process.env.GOOGLE_ACCESS_TOKEN)return process.env.GOOGLE_ACCESS_TOKEN; if(cached.token && Date.now()<cached.exp-60000)return cached.token; const sa=serviceAccount(); if(sa){ const iat=Math.floor(Date.now()/1000), exp=iat+3600; const head=b64u(JSON.stringify({alg:'RS256',typ:'JWT'})); const body=b64u(JSON.stringify({iss:sa.client_email,scope:'https://www.googleapis.com/auth/spreadsheets',aud:'https://oauth2.googleapis.com/token',iat,exp})); const sig=crypto.sign('RSA-SHA256',Buffer.from(`${head}.${body}`),sa.private_key).toString('base64url'); const r=await fetch('https://oauth2.googleapis.com/token',{method:'POST',headers:{'content-type':'application/x-www-form-urlencoded'},body:new URLSearchParams({grant_type:'urn:ietf:params:oauth:grant-type:jwt-bearer',assertion:`${head}.${body}.${sig}`})}); const j=await r.json(); if(!r.ok)throw new Error(`Google auth ${r.status}: ${JSON.stringify(j)}`); cached={token:j.access_token,exp:Date.now()+j.expires_in*1000}; return j.access_token; }
 const {GOOGLE_OAUTH_CLIENT_ID:id,GOOGLE_OAUTH_CLIENT_SECRET:secret,GOOGLE_OAUTH_REFRESH_TOKEN:refresh}=process.env; if(id&&secret&&refresh){ const r=await fetch('https://oauth2.googleapis.com/token',{method:'POST',headers:{'content-type':'application/x-www-form-urlencoded'},body:new URLSearchParams({client_id:id,client_secret:secret,refresh_token:refresh,grant_type:'refresh_token'})}); const j=await r.json(); if(!r.ok)throw new Error(`Google OAuth ${r.status}: ${JSON.stringify(j)}`); cached={token:j.access_token,exp:Date.now()+j.expires_in*1000}; return j.access_token; }
 throw new Error('No Google Sheets credential configured'); }
async function api(url,opts={}){ const t=await token(); const r=await fetch(url,{...opts,headers:{authorization:`Bearer ${t}`,'content-type':'application/json',...(opts.headers||{})}}); const text=await r.text(); let j={}; try{j=text?JSON.parse(text):{}}catch{j={raw:text}} if(!r.ok)throw new Error(`Sheets API ${r.status}: ${JSON.stringify(j).slice(0,2000)}`); return j; }
const sid=()=>{if(!process.env.SPREADSHEET_ID)throw new Error('SPREADSHEET_ID missing');return process.env.SPREADSHEET_ID};
export async function readRange(range){ const u=`https://sheets.googleapis.com/v4/spreadsheets/${sid()}/values/${encodeURIComponent(range)}?majorDimension=ROWS&valueRenderOption=UNFORMATTED_VALUE&dateTimeRenderOption=FORMATTED_STRING`; return (await api(u)).values||[]; }
export async function writeRange(range,values){ const u=`https://sheets.googleapis.com/v4/spreadsheets/${sid()}/values/${encodeURIComponent(range)}?valueInputOption=RAW`; return api(u,{method:'PUT',body:JSON.stringify({range,majorDimension:'ROWS',values})}); }
export async function appendRows(range,values){ const u=`https://sheets.googleapis.com/v4/spreadsheets/${sid()}/values/${encodeURIComponent(range)}:append?valueInputOption=RAW&insertDataOption=INSERT_ROWS`; return api(u,{method:'POST',body:JSON.stringify({majorDimension:'ROWS',values})}); }
export async function table(sheet,lastCol='ZZ',maxRows=1000){ const vals=await readRange(`${sheet}!A3:${lastCol}${maxRows}`); const headers=vals[0]||[]; return {sheet,headers,map:headerMap(headers),rows:vals.slice(1).map((r,i)=>objFromRow(headers,r,i+4))}; }
export async function updateObject(sheet,headers,rowNumber,obj){ const last=colName(headers.length); await writeRange(`${sheet}!A${rowNumber}:${last}${rowNumber}`,[rowFromObj(headers,obj)]); }
export function colName(n){let s='';for(let x=n;x>0;x=Math.floor((x-1)/26))s=String.fromCharCode(65+(x-1)%26)+s;return s;}
export async function config(){ const t=await table('ENGINE_CONFIG','E',250); const out={}; for(const r of t.rows){ if(!r.Key)continue; if(String(r.Active).toLowerCase()==='false')continue; out[r.Key]=r.Value; } return out; }
